const SET_ALERT = "SET_ALERT";

const REMOVE_ALERT = "REMOVE_ALERT";

const REGISTER_SUCCESS = "REGISTER_SUCCESS";

const REGISTER_FAIL = "REGISTER_FAIL";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";

const LOGIN_FAIL = "LOGIN_FAIL";

const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

const AUTHENTICATION_FAIL = "AUTHENTICATIOIN_FAIL";

const LOGOUT = "LOGOUT";

const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

const PROFILE_ERROR = "PROFILE_ERROR";

const CLEAR_PROFILE = "CLEAR_PROFILE";

const NEW_PROFILE_CREATED = "NEW_PROFILE_CREATED";

const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";

export {
	SET_ALERT,
	REMOVE_ALERT,
	REGISTER_SUCCESS,
	REGISTER_FAIL,
	LOGIN_FAIL,
	LOGIN_SUCCESS,
	AUTHENTICATION_SUCCESS,
	AUTHENTICATION_FAIL,
	LOGOUT,
	GET_PROFILE_SUCCESS,
	PROFILE_ERROR,
	CLEAR_PROFILE,
	CREATE_PROFILE_ERROR,
	NEW_PROFILE_CREATED,
};
