const SET_ALERT = "SET_ALERT";

const REMOVE_ALERT = "REMOVE_ALERT";

const REGISTER_SUCCESS = "REGISTER_SUCCESS";

const REGISTER_FAIL = "REGISTER_FAIL";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";

const LOGIN_FAIL = "LOGIN_FAIL";

const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

const AUTHENTICATION_FAIL = "AUTHENTICATIOIN_FAIL";

const LOGOUT = "LOGOUT";

export {
	SET_ALERT,
	REMOVE_ALERT,
	REGISTER_SUCCESS,
	REGISTER_FAIL,
	LOGIN_FAIL,
	LOGIN_SUCCESS,
	AUTHENTICATION_SUCCESS,
	AUTHENTICATION_FAIL,
	LOGOUT,
};
